// <auto-generated />
using System;
using MessagingTool.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessagingTool.Repository.Migrations
{
    [DbContext(typeof(MessagingToolDbContext))]
    partial class MessagingToolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessagingTool.Repository.Entities.CustomerMessageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerPhoneNumberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageSentOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhoneNumberId");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("MessagingTool.Repository.Entities.CustomerPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoNotCall")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("MessagingTool.Repository.Entities.CustomerMessageLog", b =>
                {
                    b.HasOne("MessagingTool.Repository.Entities.CustomerPhoneNumber", "CustomerPhoneNumber")
                        .WithMany("CustomerMessageLogs")
                        .HasForeignKey("CustomerPhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerPhoneNumber");
                });

            modelBuilder.Entity("MessagingTool.Repository.Entities.CustomerPhoneNumber", b =>
                {
                    b.Navigation("CustomerMessageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
